# Generated by Django 3.1 on 2021-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0002_auto_20210615_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='user.Employee'),
        ),
    ]
