# Generated by Django 3.1 on 2021-06-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210615_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companys'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
