# Generated by Django 3.1 on 2021-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210615_2338'),
        ('company', '0005_auto_20210616_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, to='user.Employee'),
        ),
    ]
