# Generated by Django 3.1 on 2021-06-15 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=18)),
                ('user_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
