# Generated by Django 3.1 on 2021-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210615_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
